// <auto-generated />
using System;
using LoanApplicationPlatform.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanApplicationPlatform.API.Migrations
{
    [DbContext(typeof(LoanApplicationPlatformContext))]
    [Migration("20260804052743_AddLoanApplicationStatusHistory")]
    partial class AddLoanApplicationStatusHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.LoanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("TermInMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("TenantId");

                    b.ToTable("LoanApplications");
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.LoanApplicationStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("LoanApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("LoanApplicationId");

                    b.HasIndex("TenantId");

                    b.ToTable("LoanApplicationStatusHistories");
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.PaymentSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SubmittedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoanApplicationId");

                    b.HasIndex("TenantId");

                    b.ToTable("PaymentSchedules");
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tenant 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tenant 2"
                        });
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.Treasury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Treasury");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1000000m,
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 2000000m,
                            TenantId = 2
                        });
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.TreasuryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TreasuryTransactions");
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$0IAZiPtgMtoVLj7FFEC4YewGS1HZeelrFS66dmExWVaeeirTLHjey",
                            Role = "Admin",
                            TenantId = 1,
                            Username = "t1_admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$0IAZiPtgMtoVLj7FFEC4YewGS1HZeelrFS66dmExWVaeeirTLHjey",
                            Role = "Applicant",
                            TenantId = 1,
                            Username = "t1_applicant"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$0IAZiPtgMtoVLj7FFEC4YewGS1HZeelrFS66dmExWVaeeirTLHjey",
                            Role = "Reviewer",
                            TenantId = 1,
                            Username = "t1_reviewer"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "$2a$11$0IAZiPtgMtoVLj7FFEC4YewGS1HZeelrFS66dmExWVaeeirTLHjey",
                            Role = "Approver",
                            TenantId = 1,
                            Username = "t1_approver"
                        },
                        new
                        {
                            Id = 5,
                            PasswordHash = "$2a$11$0IAZiPtgMtoVLj7FFEC4YewGS1HZeelrFS66dmExWVaeeirTLHjey",
                            Role = "Admin",
                            TenantId = 2,
                            Username = "t2_admin"
                        },
                        new
                        {
                            Id = 6,
                            PasswordHash = "$2a$11$0IAZiPtgMtoVLj7FFEC4YewGS1HZeelrFS66dmExWVaeeirTLHjey",
                            Role = "Applicant",
                            TenantId = 2,
                            Username = "t2_applicant"
                        },
                        new
                        {
                            Id = 7,
                            PasswordHash = "$2a$11$0IAZiPtgMtoVLj7FFEC4YewGS1HZeelrFS66dmExWVaeeirTLHjey",
                            Role = "Reviewer",
                            TenantId = 2,
                            Username = "t2_reviewer"
                        },
                        new
                        {
                            Id = 8,
                            PasswordHash = "$2a$11$0IAZiPtgMtoVLj7FFEC4YewGS1HZeelrFS66dmExWVaeeirTLHjey",
                            Role = "Approver",
                            TenantId = 2,
                            Username = "t2_approver"
                        });
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.LoanApplication", b =>
                {
                    b.HasOne("LoanApplicationPlatform.API.Entities.User", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanApplicationPlatform.API.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.LoanApplicationStatusHistory", b =>
                {
                    b.HasOne("LoanApplicationPlatform.API.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanApplicationPlatform.API.Entities.LoanApplication", "LoanApplication")
                        .WithMany()
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanApplicationPlatform.API.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("LoanApplication");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.PaymentSchedule", b =>
                {
                    b.HasOne("LoanApplicationPlatform.API.Entities.LoanApplication", "LoanApplication")
                        .WithMany("PaymentSchedules")
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanApplicationPlatform.API.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoanApplication");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.Treasury", b =>
                {
                    b.HasOne("LoanApplicationPlatform.API.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.TreasuryTransaction", b =>
                {
                    b.HasOne("LoanApplicationPlatform.API.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.User", b =>
                {
                    b.HasOne("LoanApplicationPlatform.API.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoanApplicationPlatform.API.Entities.LoanApplication", b =>
                {
                    b.Navigation("PaymentSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
